version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ops_db
    restart: "no"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: ops_documents
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ops_backend
    restart: "no"
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/ops_documents?schema=public
      - JWT_SECRET=supersecretjwtkey
    depends_on:
      - db

volumes:
  pgdata:
