version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ops_db
    restart: "no"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: ops_documents
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ops_backend
    restart: "no"
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/ops_documents?schema=public
      - JWT_SECRET=ese_norte3_jwt_secret_key_2026_f26
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db

  web-admin:
    image: node:22-alpine
    container_name: ops_web_admin
    working_dir: /app
    volumes:
      - ./web-admin:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

volumes:
  pgdata:

